version: '3.8'
services:
  service2:
    build: 
      context: src
      dockerfile: Dockerfile
    ports:
      - "8610"
    env_file:
      - .env
    depends_on:
      - nginx
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
  redis:
    build: 
      context: redis
      dockerfile: Dockerfile
    ports:
      - "6378:6379"
