version: '3'
services:
  service2:
    build: ./src
    ports:
      - "5000"
    env_file:
      - ./src/.env
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service2
    ports:
      - "80:80"